import Foundation
import Combine

/// The app-level switches, as SwiftUI sees them.
///
/// A thin face over `ConfigFileStore` — **`~/.config/trill/config.json` is the
/// source of truth**, and this type only publishes it and writes back to it. A
/// toggle in Settings and a line typed into the file are the same act, and an
/// edit made while trill is running lands on screen without a restart.
///
/// What stays in UserDefaults is what a settings file has no business holding:
/// the one-shot flags the Full Disk Access flow arms across a relaunch, and
/// the bundle path the login-item registration is keyed on. Ephemera, not
/// settings.
///
/// Anything a rule can express lives in `rules.json` instead.
@MainActor
final class AppSettings: ObservableObject {
    @Published var launchAtLogin: Bool {
        didSet {
            guard !isApplyingFileChange, launchAtLogin != oldValue else { return }
            guard commit(\.launchAtLogin, launchAtLogin, revert: { self.launchAtLogin = oldValue })
            else { return }
            if launchAtLogin {
                SystemIntegration.registerAsLoginItem()
            } else {
                SystemIntegration.unregisterLoginItem()
            }
        }
    }

    @Published var persistHistory: Bool {
        didSet {
            guard !isApplyingFileChange, persistHistory != oldValue else { return }
            commit(\.persistHistory, persistHistory, revert: { self.persistHistory = oldValue })
        }
    }

    @Published var systemMirrorEnabled: Bool {
        didSet {
            guard !isApplyingFileChange, systemMirrorEnabled != oldValue else { return }
            commit(\.systemMirrorEnabled, systemMirrorEnabled, revert: { self.systemMirrorEnabled = oldValue })
        }
    }

    @Published var githubBridgeEnabled: Bool {
        didSet {
            guard !isApplyingFileChange, githubBridgeEnabled != oldValue else { return }
            commit(\.githubBridgeEnabled, githubBridgeEnabled, revert: { self.githubBridgeEnabled = oldValue })
        }
    }

    /// Cards degrade to their redacted form while macOS says the screen is
    /// being watched. The reading itself is `ScreenWatchSentinel`'s; this is
    /// only whether trill acts on it.
    @Published var shyWhenWatched: Bool {
        didSet {
            guard !isApplyingFileChange, shyWhenWatched != oldValue else { return }
            commit(\.shyWhenWatched, shyWhenWatched, revert: { self.shyWhenWatched = oldValue })
        }
    }

    @Published var calendarEnabled: Bool {
        didSet {
            guard !isApplyingFileChange, calendarEnabled != oldValue else { return }
            guard commit(\.calendarEnabled, calendarEnabled, revert: { self.calendarEnabled = oldValue })
            else { return }
            // The permission sheet belongs to the click that asked for it. Left
            // to `CalendarProvider.probe()`, it would appear whenever the
            // supervisor's backoff next came round — up to a minute later,
            // which reads as trill being broken rather than as macOS asking.
            if calendarEnabled, CalendarProvider.authorization == .notDetermined {
                Task { await CalendarProvider.requestAccess() }
            }
        }
    }

    @Published var calendarLeadMinutes: Int {
        didSet {
            guard !isApplyingFileChange, calendarLeadMinutes != oldValue else { return }
            commit(\.calendarLeadMinutes, calendarLeadMinutes, revert: { self.calendarLeadMinutes = oldValue })
        }
    }

    /// Why the last write didn't land, if it didn't. Settings shows it rather
    /// than leaving a switch that moved over a file that didn't.
    @Published private(set) var writeError: String?

    /// Set when the FDA assistant flow is triggered so that if the user or
    /// macOS quits & relaunches Trill, Settings re-opens automatically to show
    /// status. UI ephemera: it is about one flow in flight, not about how
    /// trill is configured, so it stays out of the file.
    @Published var reopenSettingsOnLaunch: Bool {
        didSet {
            defaults.set(reopenSettingsOnLaunch, forKey: Keys.reopenSettingsOnLaunch)
            defaults.synchronize()
        }
    }

    /// True when the file trill would write is generated by this Mac's
    /// desktop. Settings renders every switch read-only and says where the
    /// real dial is.
    var isManagedExternally: Bool { store.isManagedExternally }

    /// Where the switches actually live — shown in Settings, because a
    /// file-backed app that never tells you the path is a file-backed app you
    /// can't edit.
    var configFileURL: URL { store.fileURL }

    private let store: ConfigFileStore
    private let defaults: UserDefaults
    /// True while a change *from the file* is being pushed into the published
    /// properties — without it, applying an external edit would write the same
    /// values straight back out.
    private var isApplyingFileChange = false

    private enum Keys {
        static let reopenSettingsOnLaunch = "reopenSettingsOnLaunch"
        static let loginItemBundlePath = "loginItemBundlePath"
    }

    init(store: ConfigFileStore = .shared, defaults: UserDefaults = .standard) {
        self.store = store
        self.defaults = defaults

        // One-time move of anything the UserDefaults-backed builds stored, so
        // an existing install keeps its switches when the file becomes the
        // truth. Runs before the first read: after it, the file is the only
        // place these values live.
        Self.migrateFromDefaults(defaults, into: store)

        let config = store.current()
        launchAtLogin = config.launchAtLogin
        persistHistory = config.persistHistory
        systemMirrorEnabled = config.systemMirrorEnabled
        githubBridgeEnabled = config.githubBridgeEnabled
        shyWhenWatched = config.shyWhenWatched
        calendarEnabled = config.calendarEnabled
        calendarLeadMinutes = config.calendarLeadMinutes
        reopenSettingsOnLaunch = defaults.bool(forKey: Keys.reopenSettingsOnLaunch)

        store.start { [weak self] config in
            Task { @MainActor in self?.apply(config) }
        }

        syncLoginItemRegistration()
    }

    /// Push a change that came from the file into the published properties,
    /// without writing it back out.
    private func apply(_ config: AppConfig) {
        isApplyingFileChange = true
        defer { isApplyingFileChange = false }
        let loginChanged = config.launchAtLogin != launchAtLogin
        // Same reason as the toggle's own didSet: the file is the truth, so
        // typing `"calendar": true` into it has to ask macOS for the grant
        // just as clicking the switch does.
        let calendarTurnedOn = config.calendarEnabled && !calendarEnabled
        launchAtLogin = config.launchAtLogin
        persistHistory = config.persistHistory
        systemMirrorEnabled = config.systemMirrorEnabled
        githubBridgeEnabled = config.githubBridgeEnabled
        shyWhenWatched = config.shyWhenWatched
        calendarEnabled = config.calendarEnabled
        calendarLeadMinutes = config.calendarLeadMinutes
        writeError = nil
        if calendarTurnedOn, CalendarProvider.authorization == .notDetermined {
            Task { await CalendarProvider.requestAccess() }
        }
        // The file is the truth for this one too: someone who writes
        // `"launchAtLogin": false` expects the login item to actually go.
        if loginChanged {
            if config.launchAtLogin {
                SystemIntegration.registerAsLoginItem()
            } else {
                SystemIntegration.unregisterLoginItem()
            }
        }
    }

    /// Write one change through to the file. On failure the published value
    /// goes back to what the file still says — a switch that stays where it
    /// was put while the file disagrees is the one outcome a file-backed
    /// settings window must not produce.
    @discardableResult
    private func commit<Value: Equatable & Sendable>(
        _ keyPath: WritableKeyPath<AppConfig, Value> & Sendable,
        _ value: Value,
        revert: () -> Void
    ) -> Bool {
        if let error = store.update({ config in config[keyPath: keyPath] = value }) {
            writeError = error.localizedDescription
            isApplyingFileChange = true
            revert()
            isApplyingFileChange = false
            return false
        }
        writeError = nil
        return true
    }

    /// Whatever the old UserDefaults-backed builds stored, written into
    /// config.json once and then removed from defaults, so there is exactly
    /// one place these live afterwards. Keys nobody ever changed are absent
    /// from defaults and stay absent from the file — a default is not a
    /// setting somebody made.
    ///
    /// **The file wins wherever it speaks.** Only keys config.json does not
    /// name are filled in from the old defaults: a value someone typed into
    /// the file — or that their desktop generated — is a later, more
    /// deliberate decision than a switch they flipped in a previous build, and
    /// a migration that overwrote it would take a machine whose settings are
    /// declared and quietly hand it the old ones instead.
    ///
    /// The legacy keys are cleared either way, including when the file can't be
    /// written at all, so this can't run again on the next launch.
    private static func migrateFromDefaults(_ defaults: UserDefaults, into store: ConfigFileStore) {
        let legacy: [(key: String, fileKey: String, keyPath: WritableKeyPath<AppConfig, Bool>)] = [
            ("launchAtLogin", AppConfig.Key.launchAtLogin, \.launchAtLogin),
            ("persistHistory", AppConfig.Key.persistHistory, \.persistHistory),
            ("systemMirrorEnabled", AppConfig.Key.systemMirror, \.systemMirrorEnabled),
            ("githubBridgeEnabled", AppConfig.Key.githubBridge, \.githubBridgeEnabled),
        ]
        let stored = legacy.filter { defaults.object(forKey: $0.key) != nil }
        guard !stored.isEmpty else { return }
        defer { for entry in stored { defaults.removeObject(forKey: entry.key) } }

        let named = store.namedKeys()
        let fillable = stored.filter { !named.contains($0.fileKey) }
        guard !fillable.isEmpty, !store.isManagedExternally else { return }
        let migrated = fillable.reduce(into: store.current()) { config, entry in
            config[keyPath: entry.keyPath] = defaults.bool(forKey: entry.key)
        }
        store.update { config in config = migrated }
    }

    /// A file trill has never been told about is a file with no login-item
    /// registration behind it — the *first* launch has to register by hand.
    /// Keyed on the bundle path rather than a one-shot flag, so a build that
    /// later moves (dev-install, or a drag from Downloads to /Applications)
    /// re-registers instead of leaving the user's Login Items pointing at a
    /// path that no longer exists.
    ///
    /// It deliberately does *not* re-register just because the entry is
    /// missing at an unchanged path: a user who removed trill in System
    /// Settings > General > Login Items meant it, and an app that silently
    /// puts itself back is the exact thing that makes that pane untrustworthy.
    private func syncLoginItemRegistration() {
        // An XCTest host *is* Trill.app, run out of DerivedData — registering
        // from there aims the user's Login Items at a build directory.
        guard ProcessInfo.processInfo.environment["XCTestConfigurationFilePath"] == nil else { return }
        guard launchAtLogin else { return }

        let bundlePath = Bundle.main.bundleURL.path
        guard defaults.string(forKey: Keys.loginItemBundlePath) != bundlePath else { return }
        SystemIntegration.registerAsLoginItem()
        defaults.set(bundlePath, forKey: Keys.loginItemBundlePath)
    }
}
