#!/usr/bin/env bash
# Bake `ai/**/SKILL.md` into Swift, so `trill skill` prints the prose that
# shipped inside this binary.
#
# The family standard (the workshop's docs/agent-surface.md) wants the skill
# EMBEDDED rather than read off disk: a cask ships an `.app`, Nix ships a store
# path, the release ships a ZIP, and only embedding is uniform across all three.
# Swift has no `go:embed`, and trill's Nix package doesn't compile anything — it
# unpacks the CI-built, notarized bundle (nix/package.nix) — so there is exactly
# one build that could generate this file, and it is Xcode's. That makes the
# generated source a COMMITTED artifact and `scripts/check-skills.sh` the thing
# that stops it drifting, rather than a build phase nothing outside Xcode runs.
#
# Regenerate after editing any SKILL.md:
#
#     scripts/generate-skills.sh
#
# Usage: scripts/generate-skills.sh [output.swift] [ai-dir]
#
# Both arguments default to this checkout's real paths. They exist so
# check-skills.sh can regenerate into a temp file — and so it can point the
# generator at an `ai/` that isn't beside the script, which is what a Nix store
# path is.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
out="${1:-$root/Trill/CLI/EmbeddedSkills.swift}"
ai="${2:-$root/ai}"

[ -f "$ai/SKILL.md" ] || { echo "generate-skills.sh: no $ai/SKILL.md" >&2; exit 2; }

# name<TAB>path, the tool's own first, then every sibling directory. DISCOVERED
# rather than listed, for the reason check-skills.sh gives at length: a
# hardcoded list here is one more place to forget a second skill, and the one
# that decides what standalone users ever see.
skills="$(printf '%s\t%s\n' trill "$ai/SKILL.md")"
for dir in "$ai"/*/; do
  [ -f "$dir/SKILL.md" ] || continue
  skills="$skills
$(printf '%s\t%s' "$(basename "$dir")" "$dir/SKILL.md")"
done

emit() { printf '%s\n' "$*"; }

{
  emit "// Generated by scripts/generate-skills.sh — do not edit."
  emit "//"
  emit "// The source is ai/**/SKILL.md. Edit those, run the script, commit both:"
  emit "// scripts/check-skills.sh fails the build when this file and the Markdown"
  emit "// disagree, because a binary whose \`skill\` verb prints last week's prose is"
  emit "// worse than one that prints none — nobody can tell which they got."
  emit ""
  emit "extension TrillCLI {"
  emit "    /// Every skill this build ships, in the layout the standard fixes:"
  emit "    /// \`ai/SKILL.md\` is the tool's own, named for the tool, and each"
  emit "    /// \`ai/<name>/SKILL.md\` beside it is named for its directory."
  emit "    enum EmbeddedSkills {"
  emit "        static let all: [EmbeddedSkill] = ["

  while IFS="$(printf '\t')" read -r name skill; do
    [ -n "$name" ] || continue

    # Raw string literal, with just enough `#` that nothing in the prose can
    # close it early or interpolate. A SKILL.md is full of backslashes and
    # quotes; escaping it by hand would make the diff unreadable and the
    # escaping itself a thing that can be wrong.
    hashes='#'
    while grep -qF -- "\"\"\"$hashes" "$skill" || grep -qF -- "\\$hashes(" "$skill"; do
      hashes="$hashes#"
    done

    printf '            EmbeddedSkill(name: "%s", body: %s"""\n' "$name" "$hashes"
    cat "$skill"
    # The closing delimiter starts a line, so no indentation is stripped and
    # the body is the file byte-for-byte — minus the final newline, which
    # Swift drops and every caller puts back.
    printf '"""%s),\n' "$hashes"
  done <<EOF
$skills
EOF

  emit "        ]"
  emit "    }"
  emit "}"
} >"$out"

echo "generate-skills.sh: wrote $out"
