import AppKit
import SwiftUI

// MARK: - The panes

/// The sidebar's contents, in the order they appear.
enum SettingsPane: String, CaseIterable, Identifiable {
    case general
    case providers
    case banners
    case files

    var id: String { rawValue }

    var title: String {
        switch self {
        case .general: return "General"
        case .providers: return "Sources"
        case .banners: return "Apple’s Banners"
        case .files: return "Files"
        }
    }

    /// The line under the pane's title: what this pane is for, in one breath.
    var summary: String {
        switch self {
        case .general:
            return "How trill starts, and what it keeps."
        case .providers:
            return "Where trill's events come from, and whether each one is actually working."
        case .banners:
            return "What macOS itself still shows for the apps trill draws — trill reads this, it never writes it."
        case .files:
            return "Every dial trill has is a file you can edit. This is where they live."
        }
    }

    var symbol: String {
        switch self {
        case .general: return "gearshape.fill"
        case .providers: return "antenna.radiowaves.left.and.right"
        case .banners: return "bell.slash.fill"
        case .files: return "doc.text.fill"
        }
    }

    var tint: Color {
        switch self {
        case .general: return .gray
        case .providers: return .blue
        case .banners: return .orange
        case .files: return .purple
        }
    }
}

// MARK: - General

struct GeneralPane: View {
    @ObservedObject var settings: AppSettings

    var body: some View {
        SettingsPaneLayout(title: SettingsPane.general.title, subtitle: SettingsPane.general.summary) {
            SettingsCard {
                SettingsRow(
                    symbol: "power",
                    title: "Launch trill at login",
                    subtitle: "trill comes back in the menu bar — no window, no Dock icon. A compositor that isn’t running draws nothing."
                ) {
                    Toggle("Launch trill at login", isOn: $settings.launchAtLogin)
                        .labelsHidden()
                        .toggleStyle(.switch)
                }
                SettingsDivider()
                SettingsRow(
                    symbol: "internaldrive",
                    title: "Keep history on disk",
                    subtitle: "Off means nothing about any event ever touches disk — and the Inbox has nothing to show you."
                ) {
                    Toggle("Keep history on disk", isOn: $settings.persistHistory)
                        .labelsHidden()
                        .toggleStyle(.switch)
                }
            }
            .disabled(settings.isManagedExternally)

            SettingsWriteStatus(settings: settings)

            SettingsFootnote(
                """
                Every switch here is a line in \(settings.configFileURL.path). Edit the file \
                and trill follows it while it runs; click a switch and the file is what gets \
                written. There is no second copy.
                """
            )
        }
    }
}

/// The one thing a file-backed settings window owes the user: whether the
/// click actually reached the file. Silent on the happy path.
struct SettingsWriteStatus: View {
    @ObservedObject var settings: AppSettings

    var body: some View {
        if settings.isManagedExternally {
            SettingsNote(
                symbol: "lock.fill",
                tint: .secondary,
                text: """
                These switches are read-only on this Mac: config.json is generated by your \
                desktop and a rebuild would put it straight back. Change it where it’s declared, \
                then rebuild.
                """
            )
        } else if let error = settings.writeError {
            SettingsNote(symbol: "exclamationmark.triangle.fill", tint: .orange, text: error)
        }
    }
}

// MARK: - Sources

struct ProvidersPane: View {
    @ObservedObject var settings: AppSettings
    let status: [String: String?]
    let hasFullDiskAccess: Bool
    let celebrating: Bool
    let onRequestFullDiskAccess: () -> Void

    var body: some View {
        SettingsPaneLayout(title: SettingsPane.providers.title, subtitle: SettingsPane.providers.summary) {
            SettingsCard {
                SettingsRow(
                    symbol: "terminal.fill",
                    tint: .green,
                    title: "Socket",
                    subtitle: "The `trill` command, and anything scripted through it. Always on."
                ) {
                    ProviderHealthBadge(reason: status["socket"].flatMap { $0 })
                }
                SettingsDivider()
                SettingsRow(
                    symbol: "point.3.connected.trianglepath.dotted",
                    tint: .blue,
                    title: "GitHub Bridge",
                    subtitle: "Webhook deliveries become banners: a review request parks as an ask, an approval is done, a red run is a fault, a mention is a chat. trill listens on localhost behind your tunnel and never writes GitHub state."
                ) {
                    Toggle("GitHub Bridge", isOn: $settings.githubBridgeEnabled)
                        .labelsHidden()
                        .toggleStyle(.switch)
                        .disabled(settings.isManagedExternally)
                }
                // Health, not hope: the toggle alone promises nothing without
                // github.json and a free port, so say what's missing.
                if settings.githubBridgeEnabled, let reason = status["github"].flatMap({ $0 }) {
                    SettingsDivider()
                    ProviderReason(reason)
                }
            }

            SettingsWriteStatus(settings: settings)

            if hasFullDiskAccess {
                systemMirrorUnlocked
            } else {
                systemMirrorLocked
            }
        }
    }

    // MARK: System Mirror, unlocked

    @ViewBuilder
    private var systemMirrorUnlocked: some View {
        SettingsCard {
            SettingsRow(
                symbol: "rectangle.on.rectangle",
                tint: .green,
                title: "System Mirror (experimental)",
                subtitle: "Reads macOS’s private notification store, read-only, to redraw other apps’ banners. May stop working on any macOS update — trill stays fully useful without it."
            ) {
                Toggle("System Mirror", isOn: $settings.systemMirrorEnabled)
                    .labelsHidden()
                    .toggleStyle(.switch)
                    .disabled(settings.isManagedExternally)
            }
            SettingsDivider()
            SettingsRow(
                symbol: "lock.open.fill",
                tint: .green,
                title: celebrating ? "Unlocked — System Mirror is live" : "Full Disk Access granted",
                subtitle: nil
            ) {}
                .scaleEffect(celebrating ? 1.03 : 1, anchor: .leading)
        }
        .background(
            RoundedRectangle(cornerRadius: 10, style: .continuous)
                .fill(Color.green.opacity(celebrating ? 0.12 : 0))
        )
    }

    // MARK: System Mirror, locked

    /// Deliberately *not* a disabled switch with a button underneath: a
    /// switch that silently refuses to move reads as a bug, and a button
    /// below it reads as unrelated. Until Full Disk Access exists there is
    /// exactly one thing to do here, so the card shows exactly that —
    /// what the feature buys, the two steps to it, and one button.
    @ViewBuilder
    private var systemMirrorLocked: some View {
        VStack(alignment: .leading, spacing: 12) {
            HStack(spacing: 10) {
                ZStack {
                    RoundedRectangle(cornerRadius: 9, style: .continuous)
                        .fill(
                            LinearGradient(
                                colors: [Color.accentColor.opacity(0.85), Color.accentColor.opacity(0.45)],
                                startPoint: .topLeading,
                                endPoint: .bottomTrailing
                            )
                        )
                        .frame(width: 34, height: 34)
                    Image(systemName: "lock.fill")
                        .font(.system(size: 15, weight: .semibold))
                        .foregroundStyle(.white)
                }

                VStack(alignment: .leading, spacing: 2) {
                    Text("System Mirror")
                        .font(.subheadline)
                        .fontWeight(.semibold)
                    Text("Locked · experimental")
                        .font(.caption2)
                        .foregroundStyle(.secondary)
                }

                Spacer()
            }

            Text("Unlock it and trill redraws **every other app’s** banners in its own quiet style — Messages, Mail, Calendar, the lot. macOS keeps that store behind Full Disk Access, so it has to be granted once.")
                .font(.subheadline)
                .foregroundStyle(.secondary)
                .fixedSize(horizontal: false, vertical: true)

            VStack(alignment: .leading, spacing: 6) {
                unlockStep(1, "Grant trill Full Disk Access", isCurrent: true)
                unlockStep(2, "trill switches System Mirror on for you", isCurrent: false)
            }

            Button(action: onRequestFullDiskAccess) {
                Label("Unlock System Mirror…", systemImage: "lock.open.fill")
                    .frame(maxWidth: .infinity)
            }
            .buttonStyle(.borderedProminent)
            .controlSize(.large)

            if let reason = status["system-mirror"].flatMap({ $0 }) {
                Text(reason)
                    .font(.caption)
                    .foregroundStyle(.secondary)
                    .fixedSize(horizontal: false, vertical: true)
            }
        }
        .padding(12)
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(
            RoundedRectangle(cornerRadius: 10, style: .continuous)
                .fill(Color.accentColor.opacity(0.07))
                .overlay(
                    RoundedRectangle(cornerRadius: 10, style: .continuous)
                        .strokeBorder(Color.accentColor.opacity(0.22), lineWidth: 1)
                )
        )
    }

    private func unlockStep(_ number: Int, _ text: String, isCurrent: Bool) -> some View {
        HStack(spacing: 8) {
            ZStack {
                Circle()
                    .fill(isCurrent ? Color.accentColor : Color.secondary.opacity(0.22))
                    .frame(width: 17, height: 17)
                Text("\(number)")
                    .font(.system(size: 10, weight: .bold))
                    .foregroundStyle(isCurrent ? Color.white : Color.secondary)
            }
            Text(text)
                .font(.subheadline)
                .foregroundStyle(isCurrent ? .primary : .secondary)
        }
    }
}

/// A provider's health in one glance: healthy is a tick, unhealthy is the
/// reason, never a spinner that never stops.
struct ProviderHealthBadge: View {
    let reason: String?

    var body: some View {
        if reason == nil {
            Label("Ready", systemImage: "checkmark.circle.fill")
                .labelStyle(.titleAndIcon)
                .font(.subheadline)
                .foregroundStyle(.green)
        } else {
            Label("Off", systemImage: "exclamationmark.circle.fill")
                .labelStyle(.titleAndIcon)
                .font(.subheadline)
                .foregroundStyle(.orange)
        }
    }
}

/// Why a source that's switched on still isn't running.
struct ProviderReason: View {
    let reason: String

    init(_ reason: String) {
        self.reason = reason
    }

    var body: some View {
        HStack(alignment: .top, spacing: 11) {
            Image(systemName: "exclamationmark.triangle.fill")
                .font(.system(size: 13))
                .foregroundStyle(.orange)
                .frame(width: 18)
            Text(reason)
                .font(.subheadline)
                .foregroundStyle(.secondary)
                .fixedSize(horizontal: false, vertical: true)
            Spacer(minLength: 0)
        }
        .padding(.horizontal, 14)
        .padding(.vertical, 11)
    }
}

// MARK: - Apple's own per-app settings

/// What macOS says right now about the apps trill is meant to be quiet for.
/// Read-only by design — every button here opens System Settings, none of
/// them writes a preference (see `NotificationSettingsAudit`).
struct BannersPane: View {
    let findings: [NativeNotificationSettings]
    let scopeIsEmpty: Bool
    let unreadable: Bool
    let onRequestAuditAccess: () -> Void

    var body: some View {
        SettingsPaneLayout(title: SettingsPane.banners.title, subtitle: SettingsPane.banners.summary) {
            SettingsCard {
                if unreadable {
                    // The store lives in an Apple group container, which is
                    // TCC-protected — the same grant System Mirror needs. Say
                    // that rather than showing a reassuring green tick trill
                    // can't stand behind.
                    SettingsRow(
                        symbol: "questionmark.circle",
                        title: "Can’t tell",
                        subtitle: "trill needs Full Disk Access to read macOS’s notification settings."
                    ) {
                        // Its own button, not a pointer at the System Mirror
                        // one: that grant flips System Mirror on when it
                        // lands, and a user who came here to make the audit
                        // work didn't ask for an experimental provider.
                        Button("Grant…", action: onRequestAuditAccess)
                    }
                } else if findings.isEmpty {
                    SettingsRow(
                        symbol: scopeIsEmpty ? "list.bullet" : "checkmark.circle.fill",
                        tint: scopeIsEmpty ? .secondary : .green,
                        title: scopeIsEmpty ? "Nothing listed yet" : "Nothing doubling up",
                        subtitle: scopeIsEmpty
                            ? "No apps in rules.json, so there is nothing to check."
                            : "macOS is quiet for every listed app."
                    ) {}
                } else {
                    ForEach(Array(findings.enumerated()), id: \.element.bundleID) { index, finding in
                        if index > 0 { SettingsDivider() }
                        SettingsRow(
                            symbol: "bell.badge.fill",
                            tint: .orange,
                            title: NotificationSettingsAudit.displayName(for: finding.bundleID),
                            subtitle: finding.complaint
                        ) {
                            Button("Silence…") {
                                SystemIntegration.presentNativeBannerAssistant(findings: [finding])
                            }
                        }
                    }
                }
            }

            if findings.count > 1 {
                Button {
                    SystemIntegration.presentNativeBannerAssistant(findings: findings)
                } label: {
                    Label("Walk me through all \(findings.count)", systemImage: "bell.slash")
                        .frame(maxWidth: .infinity)
                }
                .buttonStyle(.borderedProminent)
                .controlSize(.large)
            }

            SettingsCard {
                SettingsRow(
                    symbol: "gear",
                    title: "macOS’s own dials",
                    subtitle: "Notifications is where an app’s native banner is turned off. Focus is what silences everything at once."
                ) {
                    HStack {
                        Button("Notifications…") {
                            SystemIntegration.openNotificationSettings()
                        }
                        Button("Focus…") {
                            SystemIntegration.openFocusSettings()
                        }
                    }
                }
            }

            SettingsFootnote(
                """
                trill can’t turn another app’s native banner off for you — that dial is Apple’s, \
                and trill only ever reads it. Opening the pane and showing you the two clicks is \
                the whole offer.
                """
            )
        }
    }
}

// MARK: - Files

/// Where every dial actually lives. A file-backed app that never tells you
/// the paths is a file-backed app you can't edit.
struct FilesPane: View {
    @ObservedObject var settings: AppSettings

    var body: some View {
        SettingsPaneLayout(title: SettingsPane.files.title, subtitle: SettingsPane.files.summary) {
            SettingsCard {
                FileRow(
                    symbol: "switch.2",
                    tint: .gray,
                    title: "config.json",
                    subtitle: "The switches on the General and Sources panes. Read live: edit it and trill follows without a restart.",
                    url: settings.configFileURL
                )
                SettingsDivider()
                FileRow(
                    symbol: "list.bullet.rectangle",
                    tint: .green,
                    title: "rules.json",
                    subtitle: "Which events banner, which park on the ledge, which go straight to the inbox. Everything about an event is decided here.",
                    url: AppPaths.rulesFile
                )
                SettingsDivider()
                FileRow(
                    symbol: "point.3.connected.trianglepath.dotted",
                    tint: .blue,
                    title: "github.json",
                    subtitle: "The bridge’s webhook secret and port. Needed before the GitHub source can start.",
                    url: AppPaths.configDirectory.appendingPathComponent("github.json")
                )
            }

            SettingsWriteStatus(settings: settings)

            SettingsFootnote(
                """
                All three are plain JSON in ~/.config/trill, and all three are read while trill \
                runs — nothing here needs a restart, and nothing you type is overwritten by \
                something you click.
                """
            )
        }
    }
}

/// One config file: what it holds, and the button that gets you to it.
private struct FileRow: View {
    let symbol: String
    let tint: Color
    let title: String
    let subtitle: String
    let url: URL

    private var exists: Bool {
        FileManager.default.fileExists(atPath: url.path)
    }

    var body: some View {
        SettingsRow(symbol: symbol, tint: tint, title: title, subtitle: subtitle) {
            // "Reveal" on a file that isn't there yet would open a Finder
            // window on nothing; the directory is the honest destination, and
            // it is also where you'd create it.
            Button(exists ? "Reveal" : "Open Folder") {
                if exists {
                    NSWorkspace.shared.activateFileViewerSelecting([url])
                } else {
                    try? FileManager.default.createDirectory(
                        at: url.deletingLastPathComponent(), withIntermediateDirectories: true
                    )
                    NSWorkspace.shared.open(url.deletingLastPathComponent())
                }
            }
        }
    }
}
